swiftmailer:
    url: '%env(MAILER_URL)%'
    transport: gmail
    auth_mode: login
    port: 465
    encryption: ssl
    host: smtp.gmail.com
    username: 'unknown4me22@gmail.com'
    password: 'rspvimubxiymmrie'
    spool: { type: 'memory' }
    stream_options:
        ssl:
            allow_self_signed: true
            verify_peer: false
            verify_peer_name: false

